project_name: goudpscan
before:
  hooks:
    - go mod tidy
builds:
  - id: goudpscan
    main: ./
    binary: usr/local/bin/goudpscan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archives:
  - id: ggproxy
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- title .Os }}-
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
release:
  draft: false
  replace_existing_draft: true
  prerelease: true
  mode: append
changelog:
  skip: true
